### ISSUE TITLE
mvn install error

### ISSUE THREAD

**Issue by ykzj** [thingsboard/performance-tests#10]
root@perfclnt:~/performance-tests# mvn clean install gatling:execute
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.thingsboard:performance-tests:jar:0.0.1-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-shade-plugin is missing. @ line 110, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Thingsboard Performance Tests 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.thingsboard.common:data:jar:1.1.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.thingsboard:tools:jar:1.1.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.github.mnogu:gatling-mqtt:jar:1.0.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.203 s
[INFO] Finished at: 2017-04-18T05:16:16+00:00
[INFO] Final Memory: 13M/221M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project performance-tests: Could not resolve dependencies for project org.thingsboard:performance-tests:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: org.thingsboard.common:data:jar:1.1.0-SNAPSHOT, org.thingsboard:tools:jar:1.1.0-SNAPSHOT, com.github.mnogu:gatling-mqtt:jar:1.0.0: Could not find artifact org.thingsboard.common:data:jar:1.1.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by volodymyr-babak** [comment]
Before you can compile performance tests you'll need to do 3 things:
1. Clone **https://github.com/thingsboard/gatling-mqtt** project and run **install-local-gatling-mqtt.sh** to build gatling dependency.
2. Clone main Thingsboard project **https://github.com/thingsboard/thingsboard** and execute **mvn clean install -DskipTests**. This will build dependencies required by test project to create devices.
3. Update if needed version of Thingsboard _<thingsboard.version>1.1.0-SNAPSHOT</thingsboard.version>_ in the main pom file https://github.com/thingsboard/performance-tests/blob/master/pom.xml

**Comment by volodymyr-babak** [comment]
Most probably if you'll build project today you'll need to update to  _<version>1.2.3-SNAPSHOT</version>_

**Comment by binjie9527** [comment]
BUILD FAILURE when i execurte" mvn clean install -DskipTests" ;
Thingsboard Server UI .............................. FAILURE
