### ISSUE TITLE
License Checking Problem

### ISSUE THREAD

**Issue by chunyeow** [thingsboard/performance-tests#12]
[INFO] --- license-maven-plugin:3.0:check (default) @ performance-tests ---
[INFO] Checking licenses...
[WARNING] Unknown file extension: /home/git/performance-tests/docker/Makefile
[WARNING] Missing header in: /home/git/performance-tests/docker/tb-performance-tests.yaml

Build failure due to license checking problem, Any idea on how to solve this?

**Comment by volodymyr-babak** [comment]
hi, you can fix it locally by executing command

mvn license:format

I'll fix master branch sometime today

**Comment by volodymyr-babak** [comment]
Fixed in master branch as well
