### ISSUE TITLE
Problem Testing with TB v1.3.1

### ISSUE THREAD

**Issue by chunyeow** [thingsboard/performance-tests#15]
Device creation required device type for TB 1.3.1 and above. Fix this.

Patches here:
https://github.com/chunyeow/performance-tests-tb/commit/85ba1117929bc31508356207a36d5a21fa8bde88
https://github.com/chunyeow/performance-tests-tb/commit/3f0a60bc25b3cfd4861a7330c4ecbe121b487473

**Comment by smatvienko-tb** [comment]
Closing. The actual version is 3.x.x
