### ISSUE TITLE
Data logging location of docker based version?

### ISSUE THREAD

**Issue by Rileyjs** [thingsboard/performance-tests#22]
When using the docker implementation of the performance-test tool is additional data bout the tests logged anywhere other then being printed to the console?

**Comment by WillNilges** [comment]
I would also like to know this. The documentation doesn't say.

> This plugin finds Simulation files in your project, compiles and runs them. Results will be stored inside of the target folder in a pretty format that you are able to inspect after the run

**Comment by smatvienko-tb** [comment]
Hey, regarding the [logback.xml](https://github.com/thingsboard/performance-tests/blob/master/src/main/resources/logback.xml) all logs appended to the STDOUT
You can simply use [docker logs](https://docs.docker.com/engine/reference/commandline/logs/)
` docker logs [OPTIONS] CONTAINER`
