### ISSUE TITLE
How does this test work with gatling

### ISSUE THREAD

**Issue by XiaoHanChina** [thingsboard/performance-tests#23]
If i run the docker cmd, it will only start a docker container to test with the thingsboard. But how could I export some Gatling charts.

**Comment by smatvienko-tb** [comment]
Hi, @XiaoHanChina 
Please, refet to https://thingsboard.io/docs/reference/performance-tools/#gatling

**Comment by ehsanmqn** [comment]
Dear @XiaoHanChina 
I did run the docker file and it executed successfully. Then according to the information provided in above link by you, I configured and started the gatling using mvn command. However, for the newer versions of gatling it causes error about the "execute" command. for older version causes another error. Would you please tell me which version should I use for this purpose?

**Comment by smatvienko-tb** [comment]
Hey, @ehsanmqn 
You can try the performance-test project on Java. Gatling can be useful to generate a particular load and get the MQTT metrics, but nothing about Thingsboard processing performance.
All the fancy dashboards you can find inside Thingsboard applications.
Here some examples:
![image](https://user-images.githubusercontent.com/79898499/147561336-e1971ac5-6826-4f9a-9273-e4c0d2a1dab6.png)
![image](https://user-images.githubusercontent.com/79898499/147561421-5bef2828-e5a0-41eb-bf98-2ba51848f4ca.png)

**Comment by ehsanmqn** [comment]
> Hey, @ehsanmqn You can try the performance-test project on Java. Gatling can be useful to generate a particular load and get the MQTT metrics, but nothing about Thingsboard processing performance. All the fancy dashboards you can find inside Thingsboard applications. Here some examples: ![image](https://user-images.githubusercontent.com/79898499/147561336-e1971ac5-6826-4f9a-9273-e4c0d2a1dab6.png) ![image](https://user-images.githubusercontent.com/79898499/147561421-5bef2828-e5a0-41eb-bf98-2ba51848f4ca.png)

Thank you very much for your reply. It works for me.
