### ISSUE TITLE
can the project used in cluster environment?

### ISSUE THREAD

**Issue by amy108** [thingsboard/performance-tests#27]
i have a cluster environment including 3 tb instances setup as monolithic architecture. i want to know can this project used in cluster environment? i have tried but errors occured when connected devices as follows:
![image](https://user-images.githubusercontent.com/48902828/75218887-4c1fed00-57d6-11ea-8555-13a53c9faeb5.png)
i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Connection reset by peer

**Comment by smatvienko-tb** [comment]
Hi, @amy108 
In cluster mode, you should connect to the load balancer. 
To simulate many sessions, it is necessary to spin up a few instances of performance tests for different device ranges.
