### ISSUE TITLE
HTTP vs MQTT

### ISSUE THREAD

**Issue by martin9115** [thingsboard/performance-tests#46]
Hi, is there a example of performance test comparing HTTP and MQTT ?

**Comment by smatvienko-tb** [comment]
Hi, @martin9115 
The MQTT protocol is less expensive and much faster to send. 
This is the only difference.
After the message has been delivered, there is no difference in processing speed inside Thingsboard.
The performance test shows how fast the particular instance can process the target message rate.
The latest results will be updated soon.
Stay tuned!

**Comment by martin9115** [comment]
So, it is more meaningful, to create that type of comparison on local app ?
