### ISSUE TITLE
where can find the  project  right version for matched thingsboard server ?

### ISSUE THREAD

**Issue by icoco** [thingsboard/performance-tests#47]
I see the master branch base thingsboard 3.3.3 ,  how did the test project work with backend thingsboard server 3.2.2 

I am struggle seek the  branch  3.2.2 version of the   performance-tests  project, but not found yet.

**Comment by smatvienko-tb** [comment]
Hi, @icoco 
I'm gonna catch up on this project to update the testing experience.
The general advice is to fetch the latest master and test any 3.x.x version. The objects and rest API calls are quite generic for performance tests, so it may work fine on 3.x.x.
You can find the fancy build script:
`build.sh`
and examples of how to simply run on the latest [README](https://github.com/thingsboard/performance-tests#readme) like 
`docker run -it --rm --network host --name tb-perf-test thingsboard/tb-ce-performance-test:3.3.2-SNAPSHOT`
Please, feel free to share your experience with performance tests.
