### ISSUE TITLE
failed to process "${pkg.name}.deb": missing ':' in substitution

### ISSUE THREAD

**Issue by Pramod6395** [thingsboard/performance-tests#62]
Dear Team,

We want to add our payload in source code and make new image using DockerFile. but getting below error.

Sending build context to Docker daemon  6.144kB
Step 1/6 : FROM thingsboard/openjdk11:bullseye-slim
 ---> 54317a520d7a
Step 2/6 : COPY start-tests.sh ${pkg.name}.deb /tmp/
failed to process "${pkg.name}.deb": missing ':' in substitution
![image](https://user-images.githubusercontent.com/73251890/196903403-a7fb57c8-c007-4648-8e89-0cdbcfed40af.png)

**Comment by smatvienko-tb** [comment]
Hey!

Those Dockerfile are designed to use build args provided by maven build.

Please, use or refer to the build script `build.sh` at https://github.com/thingsboard/performance-tests/blob/master/build.sh

The maven build will looks like
```
mvn license:format clean install -Ddockerfile.skip=false
```

**Comment by Pramod6395** [comment]
Hi,

we try to run the file on Ubuntu ./build.sh.

However, facing below issue .


![image](https://user-images.githubusercontent.com/73251890/199538582-3fc1b8ee-6e2d-46e8-8cd9-b6bde16a2d03.png)

**Comment by smatvienko-tb** [comment]
> Hi,
> 
> we try to run the file on Ubuntu ./build.sh.
> 
> However, facing below issue .
> 
> ![image](https://user-images.githubusercontent.com/73251890/199538582-3fc1b8ee-6e2d-46e8-8cd9-b6bde16a2d03.png)

Hey! It looks like an access permission issue. Maven said that could not clean the target folder. Try to run from scratch or clean the target folder manually for the first time. And do not build under the root user.

Have a good day!

**Comment by Pramod6395** [comment]
Hi,

Thanks for response.

Now, getting below error even we have set java 11.

![image](https://user-images.githubusercontent.com/73251890/199652003-8dad9db5-f672-493e-9022-ccb54f75ed48.png)
